language: python
python:
  - "3.9"
# command to install dependencies
install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install tox-travis
# command to run tests
script:
  - tox
  - tox -e lint
